### ISSUE TITLE
Bug in Plant3D

### ISSUE THREAD

**Issue by ZYFno996** [ENVI-coding/Envimet-INX#8]
Hi AntonelloDN! When a skp conponent is set as Plant3D by this plug-in, the exported INX model shows that the tree is in the northeast (1 grid in north and 1 grid in east) of its location in skp. I think there might be some problem in source code, such as the index of array.
The tree in skp:
![image](https://user-images.githubusercontent.com/79386690/222162298-785581e5-689e-43f1-a794-fc987c27c3fc.png)
The tree in INX:
![image](https://user-images.githubusercontent.com/79386690/222162410-1405f3bc-c192-442e-90ed-8ae2f18d70fc.png)

**Comment by AntonelloDN** [comment]
Hi @ZYFno996 thanks! It uses the centroid of the SKP component and the nearest point method. I can check it

**Comment by AntonelloDN** [comment]
Thanks @ZYFno996,
The bug is fixed. A new official release with the fix will be released in a couple of days.
If you need it as soon as possible you can find [here](https://github.com/ENVI-coding/Envimet-INX/blob/main/build/dna_envimet.rbz) the unofficial release with the fix.

**Comment by ZYFno996** [comment]
Thanks for your work, @AntonelloDN ! It's very nice of you. Hope this plug-in better..

**Comment by AntonelloDN** [comment]
The official version is already available 🙂 I will close this issue. If the error persists on your side feel free to open the issue again
